import os
import uuid
import re
from datetime import datetime
import sqlite3
from flask import Flask, request, jsonify
from dotenv import load_dotenv
from groq import Groq
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address

# Load environment variables
load_dotenv()

app = Flask(__name__)

# Enforce strict in-memory rate limiting as requested by the spec
limiter = Limiter(key_func=get_remote_address, app=app, storage_uri="memory://")

# Initialize Groq Client
groq_client = Groq(api_key=os.getenv("GROQ_API_KEY"))
DB_NAME = "audit_log.db"


def evaluate_semantic_signal(text: str) -> float:
    try:
        system_prompt = (
            "You are an expert AI content detection assistant. Analyze the semantic structure, "
            "predictability, transitions, and phrasing of the provided text. Determine the probability "
            "that this text was generated by a Large Language Model. "
            "You must respond with EXACTLY and ONLY a single floating-point number between 0.0 and 1.0, "
            "where 0.0 means completely human-written and 1.0 means completely AI-generated. Do not include "
            "any introductory text, markdown formatting, or explanation."
        )

        response = groq_client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"Analyze this text:\n\n{text}"},
            ],
            temperature=0.0,
            max_tokens=10,
        )

        raw_output = response.choices[0].message.content.strip()
        score = float(raw_output)
        return max(0.0, min(1.0, score))
    except Exception as e:
        print(f"Error evaluating Groq semantic signal: {e}")
        return 0.5


def evaluate_stylometric_signal(text: str) -> float:
    sentences = [s.strip() for s in re.split(r"[.!?]+", text) if s.strip()]
    if len(sentences) < 2:
        return 0.5

    sentence_lengths = [len(s.split()) for s in sentences]
    mean_length = sum(sentence_lengths) / len(sentence_lengths)
    variance = sum((x - mean_length) ** 2 for x in sentence_lengths) / len(
        sentence_lengths
    )

    if variance >= 50:
        stylometric_score = 0.0
    else:
        stylometric_score = 1.0 - (variance / 50.0)

    return max(0.0, min(1.0, stylometric_score))


def get_transparency_label(score: float) -> str:
    """Maps the composite confidence metric directly to calibrated UX text components."""
    if score <= 0.35:
        return "Verified Authentic: This content matches patterns consistent with original human composition and diverse linguistic structure."
    elif score <= 0.74:
        return "Linguistic Origin Unclear: This text contains a blend of stylistic patterns that prevent definitive automated attribution. Audiences are encouraged to evaluate context independently."
    else:
        return "Automated Generation Pattern Detected: This content exhibits a high density of predictable semantic structures and uniform pacing typical of AI language modeling tools."


@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute")  # Enforce protection threshold
def submit_content():
    data = request.get_json()
    if not data or "text" not in data or "creator_id" not in data:
        return jsonify({"error": "Missing required fields 'text' or 'creator_id'"}), 400

    text_content = data["text"]
    creator_id = data["creator_id"]

    groq_score = evaluate_semantic_signal(text_content)
    stylometric_score = evaluate_stylometric_signal(text_content)
    combined_score = (groq_score * 0.65) + (stylometric_score * 0.35)

    # Resolve exact user-facing transparency copy
    assigned_label = get_transparency_label(combined_score)

    content_id = str(uuid.uuid4())
    timestamp = datetime.utcnow().isoformat() + "Z"
    text_preview = text_content[:60] + "..." if len(text_content) > 60 else text_content
    lifecycle_status = "classified"

    try:
        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        cursor.execute(
            """
            INSERT INTO audit_logs (
                content_id, creator_id, timestamp, text_preview, 
                groq_score, stylometric_score, combined_score, 
                assigned_label, lifecycle_status, creator_reasoning
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
        """,
            (
                content_id,
                creator_id,
                timestamp,
                text_preview,
                groq_score,
                stylometric_score,
                combined_score,
                assigned_label,
                lifecycle_status,
                None,
            ),
        )
        conn.commit()
        conn.close()
    except Exception as db_err:
        return jsonify({"error": f"Database logging failure: {db_err}"}), 500

    return jsonify({
        "content_id": content_id,
        "creator_id": creator_id,
        "combined_score": round(combined_score, 3),
        "transparency_label": assigned_label,
        "lifecycle_status": lifecycle_status,
    }), 201


@app.route("/appeal", methods=["POST"])
def appeal_classification():
    """Allows creators to dispute automated labels and safely modifies operational state fields."""
    data = request.get_json()
    if not data or "content_id" not in data or "creator_reasoning" not in data:
        return jsonify({"error": "Missing 'content_id' or 'creator_reasoning'"}), 400

    content_id = data["content_id"]
    reasoning = data["creator_reasoning"]

    if len(reasoning.strip()) < 15:
        return jsonify({
            "error": "Appeal reasoning must be at least 15 characters long."
        }), 400

    try:
        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()

        # Check if row exists
        cursor.execute(
            "SELECT content_id FROM audit_logs WHERE content_id = ?", (content_id,)
        )
        if not cursor.fetchone():
            conn.close()
            return jsonify({
                "error": "Target content_id tracking record not found."
            }), 404

        # Execute lifecycle state mutation
        cursor.execute(
            """
            UPDATE audit_logs 
            SET lifecycle_status = 'under review', creator_reasoning = ? 
            WHERE content_id = ?
        """,
            (reasoning, content_id),
        )

        conn.commit()
        conn.close()
        return jsonify({
            "message": "Appeal successfully logged. State changed to 'under review'."
        }), 200

    except Exception as e:
        return jsonify({"error": f"Database update error: {e}"}), 500


@app.route("/log", methods=["GET"])
def get_audit_logs():
    try:
        conn = sqlite3.connect(DB_NAME)
        conn.row_factory = sqlite3.Row
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM audit_logs ORDER BY timestamp DESC")
        rows = cursor.fetchall()
        conn.close()

        logs_list = [dict(row) for row in rows]
        return jsonify(logs_list), 200
    except Exception as e:
        return jsonify({"error": f"Failed to retrieve log database: {e}"}), 500


if __name__ == "__main__":
    app.run(port=5000, debug=True)
